### PR TITLE
Milestone: Accesibility Issues 👀 

### PR DESCRIPTION
**Pull request by jicamargo**
### 👍 Thansk to **@kirube1992** for his contributions to this Accesibility review.

# Accesibility Report 🖨️ 

-   **Page titles**
	- It would be better if tittle show first "portfolio" and after company name: "JIC" ➡️ [See code here](https://github.com/jicamargo/first-mobile-portfolio/blob/da267b458428a4b657472ef2e09b3d6573574f3d/index.html#L6)
	- Add a favicon to head in index.html ➡️ [See code here](https://github.com/jicamargo/first-mobile-portfolio/blob/da267b458428a4b657472ef2e09b3d6573574f3d/index.html#L7)
	
-  **Image text alternatives**
	 - add "alt image text to cards" ➡️ [See code here](https://github.com/jicamargo/first-mobile-portfolio/blob/da267b458428a4b657472ef2e09b3d6573574f3d/index.html#L81)

-   **Text headings**
	-  _no issues found_

-   **Color contrast**
	- _no issues found_

-   **Resize**
	- _no issues found_

-   **Interaction**
	- Add a contrast background color when form fields get the focus. ➡️ [See code here](https://github.com/jicamargo/first-mobile-portfolio/blob/f20c63af5bedc5a57ab9f6e5a6c9e160cdf864ca/css/style.css#L551-L554)

-   **Moving content**
	- _no issues found_

-   **Multimedia**
	- _no issues found_

-   **The basic structure of the page**
	- _no issues found_
	
✋ Thanks any suggestion to improve this project 😃

### CODE REVIEW

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi @jicamargo, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>

</div>

You have submitted a pair programming project without commits from your other partner(s). Kindly ensure that every member of the team participates in the project evidenced by their commits.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by kirube1992** [comment]
Add alt to the images

**Comment by jicamargo** [comment]
Thank you @kirube1992 . For your collaboration.  👍

**Review by brainconnect93 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @lincoln1883 , 👋 👋  

Your project is complete! Great job for following the project requirement🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 




## To Highlight 👍

- Descriptive Pull Request title and summary. ✔️
- Portfolio project accessibility ✔️
- Color contrast ✔️
- Alternative text for images ✔️
- Good use of Github flow ✔️

color contrast check passed 👏 👏 👏 👏 

const


## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
